application.authorization.token: ${APPLICATION_AUTHORIZATION_TOKEN}
application.authorization.token.type: ${APPLICATION_AUTHORIZATION_TOKEN_TYPE:Basic}

nexus-connector.group.enabled: ${NEXUS_CONNECTOR_ENABLED:true}
nexus-connector.group.config: ${NEXUS_CONNECTOR_GROUP_CONFIG} 

github-connector.enabled: ${GITHUB_CONNECTOR_ENABLED:true}
github-connector.host: ${GITHUB_CONNECTOR_HOST:api.github.com}
github-connector.authorization.token: ${GITHUB_CONNECTOR_AUTHORIZATION_TOKEN}
github-connector.authorization.token.type: ${GITHUB_CONNECTOR_AUTHORIZATION_TOKEN_TYPE:Bearer}
github-connector.cache.ttl: ${GITHUB_CONNECTOR_CACHE_TTL:86400000}

cache.type: ${CACHE_TYPE:File system based}
cache.base-path: ${CACHE_BASE_PATH:${user.home}/Burningwave/Cache}

spring.datasource.url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username: ${JDBC_DATABASE_USERNAME:postgres}
spring.datasource.password: ${JDBC_DATABASE_PASSWORD}

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto: update

#To disable this set the environment property SCHEDULED_OPERATIONS_PING_CRON to - 
scheduled-operations.ping.cron: ${SCHEDULED_OPERATIONS_PING_CRON:0 0/25 * * * *}
scheduled-operations.ping.zone: ${SCHEDULED_OPERATIONS_PING_ZONE:UTC}

burningwave.core.static-component-container.managed-logger.repository: 'org.burningwave.core.SLF4JManagedLoggerRepository'
burningwave.core.static-component-container.modules.export-all-to-all: false
